//! Index construction: trigram posting lists (FR-4) and JSON (de)serialization (FR-5).

use crate::{Doc, Index, Result};
use std::collections::{BTreeMap, BTreeSet};

/// Every window of 3 consecutive chars of `text`, case-folded (FR-4).
/// `"Limits"` → `["lim", "imi", "mit", "its"]` — the blog's example.
/// Shared by indexing and query expansion so both sides tokenize identically.
pub fn trigrams(text: &str) -> Vec<String> {
    // [ITERATORS] Chained lazy adapters, like C# LINQ or Python generator
    // pipelines — but compiled to a plain loop with zero allocation until
    // `collect()`. `windows(3)` borrows overlapping slices instead of
    // copying, something Python's slicing can't express.
    let chars: Vec<char> = text.to_lowercase().chars().collect();
    chars.windows(3).map(|w| w.iter().collect()).collect()
}

/// Build the inverted index from deduplicated docs (FR-4, FR-5).
pub fn build(source: String, docs: Vec<Doc>) -> Index {
    let mut grams: BTreeMap<String, Vec<u32>> = BTreeMap::new();
    for doc in &docs {
        // A set per doc: a gram appearing 50 times in one file still posts
        // one doc ID. Doc IDs ascend, so pushing keeps posting lists sorted —
        // which is what makes merge-intersection (FR-7) possible later.
        let distinct: BTreeSet<String> = trigrams(&doc.content).into_iter().collect();
        for gram in distinct {
            grams.entry(gram).or_default().push(doc.id);
        }
    }
    Index {
        version: 1,
        source,
        docs,
        grams,
    }
}

/// Write the index as JSON (FR-5).
pub fn save(index: &Index, path: &str) -> Result<()> {
    // [TRAITS] `serde_json::to_string` works on *any* type implementing
    // `Serialize` — ad-hoc polymorphism via traits, resolved at compile
    // time. Python's json module inspects objects at runtime; C# reflection
    // does too (unless source-generated). Here the code is generated by
    // the derive in lib.rs, so a typo'd field is a compile error.
    std::fs::write(path, serde_json::to_string(index)?)?;
    Ok(())
}

/// Read an index back from JSON.
pub fn load(path: &str) -> Result<Index> {
    Ok(serde_json::from_str(&std::fs::read_to_string(path)?)?)
}

#[cfg(test)]
mod tests {
    use super::*;

    fn doc(id: u32, content: &str) -> Doc {
        Doc {
            id,
            paths: vec![format!("f{id}.txt")],
            hash: String::new(),
            content: content.to_string(),
        }
    }

    #[test]
    fn trigrams_match_blog_example() {
        assert_eq!(trigrams("limits"), ["lim", "imi", "mit", "its"]);
        assert_eq!(trigrams("Limits"), trigrams("limits"), "case-folded");
        assert!(trigrams("ab").is_empty(), "too short for a trigram");
    }

    #[test]
    fn posting_lists_are_sorted_and_deduped() {
        let idx = build("test".into(), vec![doc(0, "aaaa aaaa"), doc(1, "aaaa")]);
        assert_eq!(idx.grams["aaa"], vec![0, 1]);
    }

    #[test]
    fn roundtrips_through_json() {
        let idx = build("test".into(), vec![doc(0, "hello world")]);
        let path = std::env::temp_dir().join("mini-bb-roundtrip.json");
        let path = path.to_str().unwrap();
        save(&idx, path).unwrap();
        let loaded = load(path).unwrap();
        assert_eq!(loaded.grams, idx.grams);
        assert_eq!(loaded.docs[0].content, "hello world");
        let _ = std::fs::remove_file(path);
    }
}
